# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NWViZmQxZGY4MzY0ZmQ4N2IwOTRiMGIxZGZkYzhkYTIxYWVjNzVjNWU3NThkMjg5ZjgzOGJiMTYxNGEyY2FmMmIxZjg5MTYwMmFkYWNkZjYzZWY1YTE2YjAxYjFjYmQ4ZDYwODEzYmZiYjY3NjY3NTQzMGRiMWU5NjUyZWEyZGE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
